basePath: /api/v1
info:
  contact: {}
  title: Hello
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: Show all books
      tags:
      - books
swagger: "2.0"
