basePath: /api/v1
definitions:
  db.Book:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  title: Hello
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Book'
            type: array
      summary: Show all books
      tags:
      - books
swagger: "2.0"
